### ISSUE TITLE
Missing native libs in custom JRE

### ISSUE THREAD

**Issue by pstetsuk-exadel** [openjfx/javafx-maven-plugin#19]
After execute `javafx:jlink` on windows in bin folder missing native libs from `javafx.graphics.jmod`:

```
decora_sse.dll
glass.dll
javafx_font.dll
javafx_iio.dll
prism_common.dll
prism_d3d.dll
prism_sw.dll

```

**Comment by jperedadnr** [comment]
But does the image work? It does for me.

These libraries are included in the JavaFX platform jars that Maven resolves from `.m2`, the plugin doesn't use the jmods.

**Comment by pstetsuk-exadel** [comment]
No, it doesn't works on some Windows 10 machines.

```
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
        at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

After I added these DDLs manually it works.  

Also if I use OpenJFX JMODs with `jlink` these DLLs added to the image.

**Comment by jperedadnr** [comment]
You mentioned "some" machines, but not all? If the dll files are missing it should fail on all these machines.

It would be good to have a way to reproduce the issue.

**Comment by pstetsuk-exadel** [comment]
It works on mine machine. But for several customers it doesn't work.  
I'm not able to reproduce the issue.  

But the main problem is that the image that is created using JARs from maven is different from the image that is created using JMODs.

**Comment by jperedadnr** [comment]
What do you mean by "different" image? In your case, where the maven plugin produces an image that works, how is it different from the image generated with the jlink tool (assuming you use the same command line options)?

**Comment by pstetsuk-exadel** [comment]
if I use OpenJFX JMODs with jlink these DLLs are added to the image.

**Comment by jperedadnr** [comment]
And if you use the plugin, the dlls are part of the big module file, otherwise it wouldn't work for you at all. So there are two different approaches, but the result should be the same. We need to find the problem when the image fails, and what is it different in those cases.
