### ISSUE TITLE
Problem when execute generated JAR

### ISSUE THREAD

**Issue by prsolucoes** [openjfx/javafx-maven-plugin#41]
Hi,

Im getting error when execute my generated JAR:

```
java -jar target/JRPrintPreview-0.1-SNAPSHOT.jar 
```

Error:

```
java -jar target/JRPrintPreview-0.1-SNAPSHOT.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:336)
	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:269)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:758)
	at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1035)
	at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:69)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:870)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:788)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:415)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)
```

I made a demo that can be used to test:
https://github.com/prsolucoes/jrprintpreview

Test:
```
mvn clean compile package
java -jar target/JRPrintPreview-0.1-SNAPSHOT.jar 
```

Can anyone help me?

**Comment by jperedadnr** [comment]
Are you using AdoptOpenJDK by any chance? Can you try [OpenJDK](http://jdk.java.net/12/)?

**Comment by prsolucoes** [comment]
I have solved the issue. Project was updated. Only some issues created on project that couldn’t solve. Will be nice if you help me. Thanks.

**Comment by jperedadnr** [comment]
Not enough details. Please consider posting them to StackOverflow.
