### ISSUE TITLE
Error: JavaFX runtime components are missing, and are required to run this application

### ISSUE THREAD

**Issue by Nyamkhuub** [openjfx/javafx-maven-plugin#65]
JDK - OpenJDK 11 /using Intellij IDEA/

I already added javafx dependency to my pom.xml. But My jar file doesn't work.

I was trying to work my jar file by using that command.

> java -jar cookorder.1.0.jar

But I got that error:

> JavaFX runtime components are missing, and are required to run this application

How to solve that issue?

Pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>order.application</groupId>
    <artifactId>cookorder</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <name>Cook order application</name>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.version>3.8.1</maven.compiler.version>
        <maven.shade.version>3.2.1</maven.shade.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.1</version>
        </dependency>

        <!-- converting -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.6</version>
        </dependency>

        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.21</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>13</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>13</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.11</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.ojdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>19.3.0.0</version>
        </dependency>

        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.11.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.4</version>
                <configuration>
                    <mainClass>Main</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
            </plugin>
            <!-- fat jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven.shade.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>Main</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by Nyamkhuub** [comment]
I should create another main class without inheritance from Application class.
For example:
```
public class SuperMain {
    public static void main(String[] args) {
        Main.main(args);
    }
}
```

**Comment by Swapnil722Git** [comment]
> I should create another main class without inheritance from Application class.
> For example:
> 
> ```
> public class SuperMain {
>     public static void main(String[] args) {
>         Main.main(args);
>     }
> }
> ```

Great this also solved my problem.

**Comment by DanGdl** [comment]
Hi! I can't launch a "Fat Jar" via "java -jar MyApp.jar":
- error message with external launcher-class:
Exception in thread "main" java.lang.RuntimeException: Error: class org.example.Launcher is not a subclass of javafx.application.Application
at javafx.application.Application.launch(Application.java:298)
at org.example.Launcher.main(Launcher.java:5)

- error message when method 'main(args)' is inside class, that extends Application class:
Error: JavaFX runtime components are missing, and are required to run this application

Pom file here: https://github.com/DanGdl/JfxSandBox/blob/main/pom.xml
